version: "3.8"
services:
    mongo:
        expose:
            - 27017
        restart: always
        logging:
            options:
                max-size: 1g
        volumes:
            - database:/data/db
        environment:
            PUID: 1000
            PGID: 1000
            MONGO_INITDB_DATABASE: ${MONGO_DB}
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PW}
        image: mongo
    tmvisdb:
        build:
            dockerfile: Dockerfile
            tags:
                - registry.rostlab.org/rostlab/tmvisdb:latest
        environment:
            TMVIS_MONGO_HOST: mongo
            TMVIS_MONGO_PORT: 27017
            TMVIS_MONGO_USERNAME: ${MONGO_USER}
            TMVIS_MONGO_PASSWORD: ${MONGO_PW}
            TMVIS_MONGO_DB: ${MONGO_DB}

volumes:
    database:
